export { AgregarPage } from './agregar/agregar';
export { DetallePage } from './detalle/detalle';
export { EditarPage } from './editar/editar';
export { LoginPage } from './login/login';
export { HomePage } from './home/home';
export { MapaPage } from './mapa/mapa';
export { SignupPage } from './signup/signup';
export { TabsPage } from './tabs/tabs';
export { MisEventosPage } from './mis-eventos/mis-eventos';
